version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: my-app
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  backend:
    hostname: backend
    container_name: backend
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    environment:
      - MONGO_HOSTNAME=mongo
    ports:
      - "3030:3030"
    networks:
      - frontend
      - backend
    depends_on:
     - mongo

  frontend:
    hostname: frontend
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongo_data: