version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: my-app
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: